name: Python Tests

on:
  push:
    branches: [ feat/*, dev ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        cd server/python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest and coverage
      run: |
        cd server/python
        python -m pytest tests/ --cov=. --cov-report=xml --cov-fail-under=90
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./server/python/coverage.xml
        fail_ci_if_error: true
